/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ChessGUI;



/**
 *
 * @author tasma
 */
import java.awt.Font;
import java.awt.Label;

public class OptionsMenu extends javax.swing.JPanel {

    /**
     * Creates new form OptionsMenu
     */
    
    
    
    ChessGUI gui;
    public OptionsMenu(ChessGUI gui) {
        this.gui = gui;
        setFont(new java.awt.Font("Century Schoolbook L", 2, 24));
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whitePlayer = new javax.swing.JComboBox<>();
        whitePlayerText = new javax.swing.JLabel();
        blackPlayer = new javax.swing.JComboBox<>();
        blackPlayerText = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        whiteTime = new javax.swing.JComboBox<>();
        blackTime = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label4 = new java.awt.Label();

        whitePlayer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "You", "MaxiMin", "MiniMax", "Stockfish" }));
        whitePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whitePlayerActionPerformed(evt);
            }
        });

        whitePlayerText.setText("White Player");
        whitePlayerText.setFont(new Font("Lucida",Font.PLAIN,18));

        blackPlayer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "You", "MaxiMin", "MiniMax", "Stockfish" }));
        blackPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackPlayerActionPerformed(evt);
            }
        });

        blackPlayerText.setText("Black Player");
        blackPlayerText.setFont(new Font("Lucida",Font.PLAIN,18));

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        whiteTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "9:30", "9:00", "8:30", "8:00", "7:30", "7:00", "6:30", "6:00", "5:30", "5:00", "4:30", "4:00", "3:30", "3:00", "2:30", "2:00", "1:30", "1:00" }));
        whiteTime.setSelectedItem("5:00");

        blackTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "9:30", "9:00", "8:30", "8:00", "7:30", "7:00", "6:30", "6:00", "5:30", "5:00", "4:30", "4:00", "3:30", "3:00", "2:30", "2:00", "1:30", "1:00" }));
        blackTime.setSelectedItem("5:00");

        jLabel1.setText("White Time");
        jLabel1.setFont(new Font("Lucida",Font.PLAIN,18));

        jLabel2.setText("Black Time");
        jLabel2.setFont(new Font("Lucida",Font.PLAIN,18));

        label1.setText("You - A human will play as this side");
        label1.setFont(new Font("Lucida",Font.PLAIN,20));
        label1.setAlignment(Label.CENTER);

        label2.setText("MaxiMin Bot - Easy");
        label2.setFont(new Font("Lucida",Font.PLAIN,20));
        label2.setAlignment(Label.CENTER);

        label3.setText("MiniMax Bot - Medium");
        label3.setFont(new Font("Lucida",Font.PLAIN,20));
        label3.setAlignment(Label.CENTER);

        label4.setText("Stockfish - Impossible");
        label4.setFont(new Font("Lucida",Font.PLAIN,20));
        label4.setAlignment(Label.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(whitePlayerText)
                            .addComponent(jLabel1)
                            .addComponent(whiteTime, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blackPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blackTime, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blackPlayerText)
                            .addComponent(jLabel2)))
                    .addComponent(whitePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(277, 277, 277))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blackPlayerText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whitePlayerText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whitePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blackPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whiteTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blackTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void whitePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whitePlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whitePlayerActionPerformed

    private void blackPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blackPlayerActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        Player white = null;
        Player black = null;
        
        //get white player
        
        switch(whitePlayer.getSelectedItem().toString())
        {
            case "You":
                white = new Human(true);
                break;
            case "MaxiMin":
                white = new MaxiMinBot(true);
                break;
            case "MiniMax":
                white = new MiniMaxBot(true);
                break;
            case "Stockfish":
                white = new Stockfish(true);
                break;
        }
        
        switch(blackPlayer.getSelectedItem().toString())
        {
            case "You":
                black = new Human(false);
                break;
            case "MaxiMin":
                black = new MaxiMinBot(false);
                break;
            case "MiniMax":
                black = new MiniMaxBot(false);
                break;
            case "Stockfish":
                black = new Stockfish(false);
                break;
        }
        
        int sumWhiteSeconds = 0;
        int sumBlackSeconds = 0;
        
        switch (whiteTime.getSelectedItem().toString()) {
            case "10:00":
                sumWhiteSeconds += 30;
            case "9:30":
                sumWhiteSeconds += 30;
            case "9:00":
                sumWhiteSeconds += 30;
            case "8:30":
                sumWhiteSeconds += 30;
            case "8:00":
                sumWhiteSeconds += 30;
            case "7:30":
                sumWhiteSeconds += 30;
            case "7:00":
                sumWhiteSeconds += 30;
            case "6:30":
                sumWhiteSeconds += 30;
            case "6:00":
                sumWhiteSeconds += 30;
            case "5:30":
                sumWhiteSeconds += 30;
            case "5:00":
                sumWhiteSeconds += 30;
            case "4:30":
                sumWhiteSeconds += 30;
            case "4:00":
                sumWhiteSeconds += 30;
            case "3:30":
                sumWhiteSeconds += 30;
            case "3:00":
                sumWhiteSeconds += 30;
            case "2:30":
                sumWhiteSeconds += 30;
            case "2:00":
                sumWhiteSeconds += 30;
            case "1:30":
                sumWhiteSeconds += 30;
            case "1:00":
                sumWhiteSeconds += 60;
        };
        
        switch (blackTime.getSelectedItem().toString()) {
            case "10:00":
                sumBlackSeconds += 30;
            case "9:30":
                sumBlackSeconds += 30;
            case "9:00":
                sumBlackSeconds += 30;
            case "8:30":
                sumBlackSeconds += 30;
            case "8:00":
                sumBlackSeconds += 30;
            case "7:30":
                sumBlackSeconds += 30;
            case "7:00":
                sumBlackSeconds += 30;
            case "6:30":
                sumBlackSeconds += 30;
            case "6:00":
                sumBlackSeconds += 30;
            case "5:30":
                sumBlackSeconds += 30;
            case "5:00":
                sumBlackSeconds += 30;
            case "4:30":
                sumBlackSeconds += 30;
            case "4:00":
                sumBlackSeconds += 30;
            case "3:30":
                sumBlackSeconds += 30;
            case "3:00":
                sumBlackSeconds += 30;
            case "2:30":
                sumBlackSeconds += 30;
            case "2:00":
                sumBlackSeconds += 30;
            case "1:30":
                sumBlackSeconds += 30;
            case "1:00":
                sumBlackSeconds += 60;
        };
        
        
        
        
        final int whiteSeconds = sumWhiteSeconds;
        final int blackSeconds = sumBlackSeconds;
        
        
        Chess chessgame = new Chess(white, black);
        
        GamePanel gamePanel = new GamePanel(gui, chessgame);
        gui.changeActivePanel(gamePanel);
        Thread gameThread = new Thread(){
            @Override
            public void run()
            {
                chessgame.play(whiteSeconds,blackSeconds);
            }
        };
        gameThread.start();
    }//GEN-LAST:event_playButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> blackPlayer;
    private javax.swing.JLabel blackPlayerText;
    private javax.swing.JComboBox<String> blackTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JButton playButton;
    private javax.swing.JComboBox<String> whitePlayer;
    private javax.swing.JLabel whitePlayerText;
    private javax.swing.JComboBox<String> whiteTime;
    // End of variables declaration//GEN-END:variables
}
